### ISSUE TITLE
Requesting membership into newly formed ksh-community

### ISSUE THREAD

**Issue by hyenias** [hyenias/temp#1]
@jghub: I would like to join the newly created ksh-community. I am new to github and ksh. I have been wanting to contribute to an open source community and had selected KornShell to grow my skills. My initial expectations with contributing to ast-ksh was to help document KornShell by improving internal documentation, website, and its wiki. Plus along-the-way, assist with issues if I had enough comfort level to reply. Medium range plans are to assist in merging in bug fixes into the existing code base as well as fixing some usability gaps in some commands/functions. My long range plans are to gain enough internal knowledge of the inter-workings of the shell language code base to potentially make some add-ins.

**Comment by jghub** [comment]
@hyenias:
thank you for your message. you are definitely the first one to express interest to join. after talking to the other guys it was agreed that we invite you to become a member so that you can participate in internal discussions and distribution of tasks.  documentation and the like sure is a good starting point.

overall, you sure are aware that this whole effort is just  starting up and needs further administrative setup before the real work can begin. 

in any case I will now try to find the correct button to push in the ksh-community  web page to invite you (I myself definitely am not a regular user of github (and an active avoider of git if it can be helped ...). everything else: later.

**Comment by hyenias** [comment]
request successful.
